from app.models import db, ClassSession

classes = [
    {
        'id': 1,
        'title': 'Adult Beginner',
        'imageUrl': 'https://www.thebxngclub.com/sites/default/files/styles/post_teaser_full/public/teasers/Guy-Kicking-in-Muay-Thai.jpg?itok=2v6sRyex',
        'time': '8:00 - 9:00 AM',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Nisl nisi scelerisque eu ultrices vitae auctor eu augue.',
        'cost': 4,
        'gym_id': 1,
    },
    {
        'id': 2,
        'title': 'Adults Mixed levels',
        'imageUrl': 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fgetbackintofitness.com%2Fwp-content%2Fuploads%2F2020%2F01%2Fkickboxing-for-beginners.jpg&f=1&nofb=1',
        'time': '7:00 - 8:00 PM',
        'description': 'Nisl purus in mollis nunc sed id semper risus. Volutpat sed cras ornare arcu. Nec feugiat nisl pretium fusce id velit ut tortor. Etiam sit amet nisl purus in mollis. Elementum integer enim neque volutpat. Aliquam sem fringilla ut morbi tincidunt augue. ',
        'cost': 4,
        'gym_id': 2,
    },
    {
        'id': 3,
        'title': 'Adult Intermediate & Advance ',
        'imageUrl': 'https://i1.wp.com/www.warriorcollective.co.uk/wp-content/uploads/2019/07/GW-3-Web.jpg?fit=1366%2C911&ssl=1',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 3,
    },
    {
        'id': 4,
        'title': 'Muay Thai Basics',
        'imageUrl': 'https://www.apexmartialartscenter.com/wp-content/uploads/beginners-kickboxing-1024x600.jpg',
        'time': '8:00 - 9:00 AM',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Nisl nisi scelerisque eu ultrices vitae auctor eu augue.',
        'cost': 4,
        'gym_id': 2,
    },
    {
        'id': 5,
        'title': 'Muay Thai Bag Drills',
        'imageUrl': 'https://bambammartialartshouston.com/wp-content/uploads/2018/03/Muay-Thai-Bag-Training.jpg',
        'time': '12:00 - 1:00 PM',
        'description': 'Nisl purus in mollis nunc sed id semper risus. Volutpat sed cras ornare arcu. Nec feugiat nisl pretium fusce id velit ut tortor. Etiam sit amet nisl purus in mollis. Elementum integer enim neque volutpat. Aliquam sem fringilla ut morbi tincidunt augue. ',
        'cost': 4,
        'gym_id': 1,
    },
    {
        'id': 6,
        'title': 'Muay Thai Pad Work',
        'imageUrl': 'http://www.teamscorpionmma.com/wp-content/uploads/2018/09/kickboxing-classes.png',
        'time': '8:00 - 9:00PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 1,
    },
    {
        'id': 7,
        'title': 'Muay Thai Techniques and Drills',
        'imageUrl': 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.warriorcollective.co.uk%2Fwp-content%2Fuploads%2F2018%2F02%2FDT-22-Copy-Web-980x654.jpg&f=1&nofb=1',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 2,
    },
    {
        'id': 8,
        'title': 'Muay Thai Sparring',
        'imageUrl': 'https://www.muaythaicitizen.com/wp-content/uploads/2018/02/muay-thai-sparring.jpg',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 8,
        'gym_id': 5,
    },
    {
        'id': 9,
        'title': 'Adult Beginner',
        'imageUrl': 'https://www.thebxngclub.com/sites/default/files/styles/post_teaser_full/public/teasers/Guy-Kicking-in-Muay-Thai.jpg?itok=2v6sRyex',
        'time': '8:00 - 9:00 AM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': '7',
    },
    {
        'id': 10,
        'title': 'Adults Mixed levels',
        'imageUrl': 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fgetbackintofitness.com%2Fwp-content%2Fuploads%2F2020%2F01%2Fkickboxing-for-beginners.jpg&f=1&nofb=1',
        'time': '7:00 - 8:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 9,
    },
    {
        'id': 11,
        'title': 'Adult Intermediate & Advance ',
        'imageUrl': 'https://i1.wp.com/www.warriorcollective.co.uk/wp-content/uploads/2019/07/GW-3-Web.jpg?fit=1366%2C911&ssl=1',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 14,
    },
    {
        'id': 12,
        'title': 'Muay Thai Basics',
        'imageUrl': 'https://www.apexmartialartscenter.com/wp-content/uploads/beginners-kickboxing-1024x600.jpg',
        'time': '8:00 - 9:00 AM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 18,
    },
    {
        'id': 13,
        'title': 'Muay Thai Bag Drills',
        'imageUrl': 'https://bambammartialartshouston.com/wp-content/uploads/2018/03/Muay-Thai-Bag-Training.jpg',
        'time': '12:00 - 1:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 17,
    },
    {
        'id': 14,
        'title': 'Muay Thai Pad Work',
        'imageUrl': 'http://www.teamscorpionmma.com/wp-content/uploads/2018/09/kickboxing-classes.png',
        'time': '8:00 - 9:00PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 4,
    },
    {
        'id': 15,
        'title': 'Muay Thai Techniques and Drills',
        'imageUrl': 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.warriorcollective.co.uk%2Fwp-content%2Fuploads%2F2018%2F02%2FDT-22-Copy-Web-980x654.jpg&f=1&nofb=1',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 3,
    },
    {
        'id': 16,
        'title': 'Muay Thai Sparring',
        'imageUrl': 'https://www.muaythaicitizen.com/wp-content/uploads/2018/02/muay-thai-sparring.jpg',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 8,
        'gym_id': 6,
    },
    {
        'id': 17,
        'title': 'Adult Beginner',
        'imageUrl': 'https://www.thebxngclub.com/sites/default/files/styles/post_teaser_full/public/teasers/Guy-Kicking-in-Muay-Thai.jpg?itok=2v6sRyex',
        'time': '8:00 - 9:00 AM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 7,
    },
    {
        'id': 18,
        'title': 'Adults Mixed levels',
        'imageUrl': 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fgetbackintofitness.com%2Fwp-content%2Fuploads%2F2020%2F01%2Fkickboxing-for-beginners.jpg&f=1&nofb=1',
        'time': '7:00 - 8:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 9,
    },
    {
        'id': 19,
        'title': 'Adult Intermediate & Advance ',
        'imageUrl': 'https://i1.wp.com/www.warriorcollective.co.uk/wp-content/uploads/2019/07/GW-3-Web.jpg?fit=1366%2C911&ssl=1',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 10,
    },
    {
        'id': 20,
        'title': 'Muay Thai Basics',
        'imageUrl': 'https://www.apexmartialartscenter.com/wp-content/uploads/beginners-kickboxing-1024x600.jpg',
        'time': '8:00 - 9:00 AM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 12,
    },
    {
        'id': 21,
        'title': 'Muay Thai Bag Drills',
        'imageUrl': 'https://bambammartialartshouston.com/wp-content/uploads/2018/03/Muay-Thai-Bag-Training.jpg',
        'time': '12:00 - 1:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 18,
    },
    {
        'id': 22,
        'title': 'Muay Thai Pad Work',
        'imageUrl': 'http://www.teamscorpionmma.com/wp-content/uploads/2018/09/kickboxing-classes.png',
        'time': '8:00 - 9:00PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 19,
    },
    {
        'id': 23,
        'title': 'Muay Thai Techniques and Drills',
        'imageUrl': 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.warriorcollective.co.uk%2Fwp-content%2Fuploads%2F2018%2F02%2FDT-22-Copy-Web-980x654.jpg&f=1&nofb=1',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 12,
    },
    {
        'id': 24,
        'title': 'Muay Thai Sparring',
        'imageUrl': 'https://www.muaythaicitizen.com/wp-content/uploads/2018/02/muay-thai-sparring.jpg',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 8,
        'gym_id': 13,
    },
    {
        'id': 25,
        'title': 'Adult Beginner',
        'imageUrl': 'https://www.thebxngclub.com/sites/default/files/styles/post_teaser_full/public/teasers/Guy-Kicking-in-Muay-Thai.jpg?itok=2v6sRyex',
        'time': '8:00 - 9:00 AM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 14,
    },
    {
        'id': 26,
        'title': 'Adults Mixed levels',
        'imageUrl': 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fgetbackintofitness.com%2Fwp-content%2Fuploads%2F2020%2F01%2Fkickboxing-for-beginners.jpg&f=1&nofb=1',
        'time': '7:00 - 8:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 8,
    },
    {
        'id': 27,
        'title': 'Adult Intermediate & Advance ',
        'imageUrl': 'https://i1.wp.com/www.warriorcollective.co.uk/wp-content/uploads/2019/07/GW-3-Web.jpg?fit=1366%2C911&ssl=1',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 17,
    },
    {
        'id': 28,
        'title': 'Muay Thai Basics',
        'imageUrl': 'https://www.apexmartialartscenter.com/wp-content/uploads/beginners-kickboxing-1024x600.jpg',
        'time': '8:00 - 9:00 AM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 18,
    },
    {
        'id': 29,
        'title': 'Muay Thai Bag Drills',
        'imageUrl': 'https://bambammartialartshouston.com/wp-content/uploads/2018/03/Muay-Thai-Bag-Training.jpg',
        'time': '12:00 - 1:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 11,
    },
    {
        'id': 30,
        'title': 'Muay Thai Pad Work',
        'imageUrl': 'http://www.teamscorpionmma.com/wp-content/uploads/2018/09/kickboxing-classes.png',
        'time': '8:00 - 9:00PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 5,
    },
    {
        'id': 31,
        'title': 'Muay Thai Techniques and Drills',
        'imageUrl': 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.warriorcollective.co.uk%2Fwp-content%2Fuploads%2F2018%2F02%2FDT-22-Copy-Web-980x654.jpg&f=1&nofb=1',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 8,
    },
    {
        'id': 32,
        'title': 'Muay Thai Sparring',
        'imageUrl': 'https://www.muaythaicitizen.com/wp-content/uploads/2018/02/muay-thai-sparring.jpg',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 8,
        'gym_id': 16,
    },
    {
        'id': 33,
        'title': 'Adult Beginner',
        'imageUrl': 'https://www.thebxngclub.com/sites/default/files/styles/post_teaser_full/public/teasers/Guy-Kicking-in-Muay-Thai.jpg?itok=2v6sRyex',
        'time': '8:00 - 9:00 AM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 15,
    },
    {
        'id': 34,
        'title': 'Adults Mixed levels',
        'imageUrl': 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fgetbackintofitness.com%2Fwp-content%2Fuploads%2F2020%2F01%2Fkickboxing-for-beginners.jpg&f=1&nofb=1',
        'time': '7:00 - 8:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 6,
    },
    {
        'id': 35,
        'title': 'Adult Intermediate & Advance ',
        'imageUrl': 'https://i1.wp.com/www.warriorcollective.co.uk/wp-content/uploads/2019/07/GW-3-Web.jpg?fit=1366%2C911&ssl=1',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 10,
    },
    {
        'id': 36,
        'title': 'Muay Thai Basics',
        'imageUrl': 'https://www.apexmartialartscenter.com/wp-content/uploads/beginners-kickboxing-1024x600.jpg',
        'time': '8:00 - 9:00 AM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 9,
    },
    {
        'id': 37,
        'title': 'Muay Thai Bag Drills',
        'imageUrl': 'https://bambammartialartshouston.com/wp-content/uploads/2018/03/Muay-Thai-Bag-Training.jpg',
        'time': '12:00 - 1:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 3,
    },
    {
        'id': 38,
        'title': 'Muay Thai Pad Work',
        'imageUrl': 'http://www.teamscorpionmma.com/wp-content/uploads/2018/09/kickboxing-classes.png',
        'time': '8:00 - 9:00PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 7,
    },
    {
        'id': 39,
        'title': 'Muay Thai Techniques and Drills',
        'imageUrl': 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.warriorcollective.co.uk%2Fwp-content%2Fuploads%2F2018%2F02%2FDT-22-Copy-Web-980x654.jpg&f=1&nofb=1',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 5,
    },
    {
        'id': 40,
        'title': 'Muay Thai Sparring',
        'imageUrl': 'https://www.muaythaicitizen.com/wp-content/uploads/2018/02/muay-thai-sparring.jpg',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 8,
        'gym_id': 3,
    },
    {
        'id': 41,
        'title': 'Adult Beginner',
        'imageUrl': 'https://www.thebxngclub.com/sites/default/files/styles/post_teaser_full/public/teasers/Guy-Kicking-in-Muay-Thai.jpg?itok=2v6sRyex',
        'time': '8:00 - 9:00 AM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 2,
    },
    {
        'id': 42,
        'title': 'Adults Mixed levels',
        'imageUrl': 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fgetbackintofitness.com%2Fwp-content%2Fuploads%2F2020%2F01%2Fkickboxing-for-beginners.jpg&f=1&nofb=1',
        'time': '7:00 - 8:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 1,
    },
    {
        'id': 43,
        'title': 'Adult Intermediate & Advance ',
        'imageUrl': 'https://i1.wp.com/www.warriorcollective.co.uk/wp-content/uploads/2019/07/GW-3-Web.jpg?fit=1366%2C911&ssl=1',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 10,
    },
    {
        'id': 44,
        'title': 'Muay Thai Basics',
        'imageUrl': 'https://www.apexmartialartscenter.com/wp-content/uploads/beginners-kickboxing-1024x600.jpg',
        'time': '8:00 - 9:00 AM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 19,
    },
    {
        'id': 45,
        'title': 'Muay Thai Bag Drills',
        'imageUrl': 'https://bambammartialartshouston.com/wp-content/uploads/2018/03/Muay-Thai-Bag-Training.jpg',
        'time': '12:00 - 1:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 15,
    },
    {
        'id': 46,
        'title': 'Muay Thai Pad Work',
        'imageUrl': 'http://www.teamscorpionmma.com/wp-content/uploads/2018/09/kickboxing-classes.png',
        'time': '8:00 - 9:00PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 14,
    },
    {
        'id': 47,
        'title': 'Muay Thai Techniques and Drills',
        'imageUrl': 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.warriorcollective.co.uk%2Fwp-content%2Fuploads%2F2018%2F02%2FDT-22-Copy-Web-980x654.jpg&f=1&nofb=1',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 13,
    },
    {
        'id': 48,
        'title': 'Muay Thai Sparring',
        'imageUrl': 'https://www.muaythaicitizen.com/wp-content/uploads/2018/02/muay-thai-sparring.jpg',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 8,
        'gym_id': 7,
    },
    {
        'id': 49,
        'title': 'Adult Beginner',
        'imageUrl': 'https://www.thebxngclub.com/sites/default/files/styles/post_teaser_full/public/teasers/Guy-Kicking-in-Muay-Thai.jpg?itok=2v6sRyex',
        'time': '8:00 - 9:00 AM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 5,
    },
    {
        'id': 50,
        'title': 'Adults Mixed levels',
        'imageUrl': 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fgetbackintofitness.com%2Fwp-content%2Fuploads%2F2020%2F01%2Fkickboxing-for-beginners.jpg&f=1&nofb=1',
        'time': '7:00 - 8:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 14,
    },
    {
        'id': 51,
        'title': 'Adult Intermediate & Advance ',
        'imageUrl': 'https://i1.wp.com/www.warriorcollective.co.uk/wp-content/uploads/2019/07/GW-3-Web.jpg?fit=1366%2C911&ssl=1',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 10,
    },
    {
        'id': 52,
        'title': 'Muay Thai Basics',
        'imageUrl': 'https://www.apexmartialartscenter.com/wp-content/uploads/beginners-kickboxing-1024x600.jpg',
        'time': '8:00 - 9:00 AM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 1,
    },
    {
        'id': 53,
        'title': 'Muay Thai Bag Drills',
        'imageUrl': 'https://bambammartialartshouston.com/wp-content/uploads/2018/03/Muay-Thai-Bag-Training.jpg',
        'time': '12:00 - 1:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 3,
    },
    {
        'id': 54,
        'title': 'Muay Thai Pad Work',
        'imageUrl': 'http://www.teamscorpionmma.com/wp-content/uploads/2018/09/kickboxing-classes.png',
        'time': '8:00 - 9:00PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 5,
    },
    {
        'id': 55,
        'title': 'Muay Thai Techniques and Drills',
        'imageUrl': 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.warriorcollective.co.uk%2Fwp-content%2Fuploads%2F2018%2F02%2FDT-22-Copy-Web-980x654.jpg&f=1&nofb=1',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 6,
    },
    {
        'id': 56,
        'title': 'Muay Thai Sparring',
        'imageUrl': 'https://www.muaythaicitizen.com/wp-content/uploads/2018/02/muay-thai-sparring.jpg',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 8,
        'gym_id': 9,
    },
    {
        'id': 57,
        'title': 'Adult Beginner',
        'imageUrl': 'https://www.thebxngclub.com/sites/default/files/styles/post_teaser_full/public/teasers/Guy-Kicking-in-Muay-Thai.jpg?itok=2v6sRyex',
        'time': '8:00 - 9:00 AM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 11,
    },
    {
        'id': 58,
        'title': 'Adults Mixed levels',
        'imageUrl': 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fgetbackintofitness.com%2Fwp-content%2Fuploads%2F2020%2F01%2Fkickboxing-for-beginners.jpg&f=1&nofb=1',
        'time': '7:00 - 8:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 13,
    },
    {
        'id': 59,
        'title': 'Adult Intermediate & Advance ',
        'imageUrl': 'https://i1.wp.com/www.warriorcollective.co.uk/wp-content/uploads/2019/07/GW-3-Web.jpg?fit=1366%2C911&ssl=1',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 4,
    },
    {
        'id': 60,
        'title': 'Muay Thai Basics',
        'imageUrl': 'https://www.apexmartialartscenter.com/wp-content/uploads/beginners-kickboxing-1024x600.jpg',
        'time': '8:00 - 9:00 AM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 9,
    },
    {
        'id': 61,
        'title': 'Muay Thai Bag Drills',
        'imageUrl': 'https://bambammartialartshouston.com/wp-content/uploads/2018/03/Muay-Thai-Bag-Training.jpg',
        'time': '12:00 - 1:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 15,
    },
    {
        'id': 62,
        'title': 'Muay Thai Pad Work',
        'imageUrl': 'http://www.teamscorpionmma.com/wp-content/uploads/2018/09/kickboxing-classes.png',
        'time': '8:00 - 9:00PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 13,
    },
    {
        'id': 63,
        'title': 'Muay Thai Techniques and Drills',
        'imageUrl': 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.warriorcollective.co.uk%2Fwp-content%2Fuploads%2F2018%2F02%2FDT-22-Copy-Web-980x654.jpg&f=1&nofb=1',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 4,
        'gym_id': 6,
    },
    {
        'id': 64,
        'title': 'Muay Thai Sparring',
        'imageUrl': 'https://www.muaythaicitizen.com/wp-content/uploads/2018/02/muay-thai-sparring.jpg',
        'time': '9:00 - 10:00 PM',
        'description': 'Nullam vehicula ipsum a arcu cursus vitae congue mauris. Nibh tortor id aliquet lectus proin nibh nisl. Lacus suspendisse faucibus interdum posuere. Amet nulla facilisi morbi tempus iaculis. Nulla porttitor massa id neque aliquam vestibulum.',
        'cost': 8,
        'gym_id': 7,
    },

]


def seed_classes():
    for Class in classes:
        selectedClasses = ClassSession(**Class)
        db.session.add(selectedClasses)

    db.session.commit()


def undo_classes():
    db.session.execute('TRUNCATE class_sessions RESTART IDENTITY CASCADE;')
    db.session.commit()
